//get information from port 3000
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5MjMzNjQ5OCwiZXhwIjoxNTkyMzM2NTEzfQ.kaEUoH3xWTEWqc9aw1qXN5-4GJvzPlNCdmxqr--pjE4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5MjMzNjg1Mn0.9YXW9T1tjjMbXSgkrBCA-K8zmYSxVtpKe0yvUoc4jQc"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTU5MjMzNjg1Mn0.9YXW9T1tjjMbXSgkrBCA-K8zmYSxVtpKe0yvUoc4jQc"
}

###
//login in port 4000 (Auth)
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}